version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6
      POSTGRES_DB: youtube
    ports:
      - '5432:5432'

  api:
    build:
      context: .
    container_name: nest-api
    ports:
      - '4002:4000'
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:6@db:5432/youtube
    depends_on:
      - db
